name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  fail-fast: true
  timezone: UTC
  REQUIRED_PHP_EXTENSIONS: 'gettext json mbstring xml zlib'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v2
        coverage: pcov

#    - name: Validate composer.json
#      run: composer validate --no-check-lock

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --no-interaction

    - name: Run test suite
      run: vendor/bin/phpunit
