name: Documentation

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - build
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install tools
        run: |
          python3 -m pip install --upgrade pip
          pip install mkdocs
          pip install --upgrade --force-reinstall mkdocs-material
          pip install mkdocs-minify-plugin
      - name: Build site
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./site
